Repository sublime-security/sublime-rules, pull requests merged in 2024-07, with the labels that each got.

#1651 Update attachment_callback_phish_with_pdf.yml
  detection-rules/attachment_callback_phish_with_pdf.yml
Labels: review-needed

#1652 Update impersonation_adobe_suspicious_language_link.yml
  detection-rules/impersonation_adobe_suspicious_language_link.yml
Labels: review-needed

#1669 Create link_recipient_domain_in_path.yml
  detection-rules/link_recipient_domain_in_path.yml
Labels: in-test-rules

#1697 Create link_secure_sharepoint_file.yml
  detection-rules/link_secure_sharepoint_file.yml
Labels: in-test-rules, review-needed

#1700 Create link_sharepoint_netorgft.yml
  detection-rules/link_sharepoint_netorgft.yml
Labels: in-test-rules, review-needed

#1674 Create attachment_html_javascript_HTTP.yml
  detection-rules/attachment_html_javascript_HTTP.yml
Labels: in-test-rules, review-needed

#1695 Update body_bec_mobile_solicitation.yml
  detection-rules/body_bec_mobile_solicitation.yml
Labels: review-needed

#1706 Update open_redirect_doubleclick.yml
  detection-rules/open_redirect_doubleclick.yml
Labels: review-needed

#1708 Update link_secure_sharepoint_file.yml
  detection-rules/link_secure_sharepoint_file.yml
Labels: review-needed

#1709 Update impersonation_linkedin.yml
  detection-rules/impersonation_linkedin.yml
Labels: review-needed

#1714 Update open_redirect_vk.yml
  detection-rules/open_redirect_vk.yml
Labels: review-needed

#1712 Update spam_fake_photo_share.yml
  detection-rules/spam_fake_photo_share.yml
Labels: review-needed

#1668 Create spam_image_hidden_element.yml
  detection-rules/spam_image_hidden_element.yml
Labels: in-test-rules, review-needed

#1719 FP fix: Corp services
  detection-rules/credential_phishing_corporate_services_impersonation_with_suspicious_link.yml
Labels: review-needed

#1722 Update spam_onmicrosoft.yml
  detection-rules/spam_onmicrosoft.yml
Labels: review-needed

#1721 Update attachment_small_html_recipient_address.yml
  detection-rules/attachment_small_html_recipient_address.yml
Labels: review-needed

#1723 Update impersonation_fake_shipping_notification.yml
  detection-rules/impersonation_fake_shipping_notification.yml
Labels: review-needed

#1710 Update impersonation_human_resources.yml
  detection-rules/impersonation_human_resources.yml
Labels: review-needed

#1731 Update impersonation_sublime_security.yml
  detection-rules/impersonation_sublime_security.yml
Labels: review-needed

#1725 Update link_fake_password_expiration.yml
  detection-rules/link_fake_password_expiration.yml
Labels: review-needed

#1727 Update spam_attendee_list_solicitation.yml
  detection-rules/spam_attendee_list_solicitation.yml
Labels: review-needed

#1685 Update link_credential_phishing_voicemail_language.yml
  detection-rules/link_credential_phishing_voicemail_language.yml
Labels: review-needed

#1698 New insight: Message importance
  insights/headers/importance.yml
Labels: review-needed

#1726 Update fake_tax_prep_request.yml
  detection-rules/fake_tax_prep_request.yml
Labels: review-needed

#1730 Update spam_image_hidden_element.yml
  detection-rules/spam_image_hidden_element.yml
Labels: in-test-rules

#1740 Update cc_infra_abuse.yml
  detection-rules/cc_infra_abuse.yml
Labels: review-needed

#1737 Update impersonation_employee_urgent_request.yml
  detection-rules/impersonation_employee_urgent_request.yml
Labels: review-needed

#1707 Create open_redirect_nested_doubleclick.yml
  detection-rules/open_redirect_nested_doubleclick.yml
Labels: in-test-rules, review-needed

#1738 Update impersonation_ups.yml
  detection-rules/impersonation_ups.yml
Labels: review-needed

#1736 Update link_credential_phishing_intent_and_other_indicators.yml
  detection-rules/link_credential_phishing_intent_and_other_indicators.yml
Labels: review-needed

#1735 Update link_fake_password_expiration.yml
  detection-rules/link_fake_password_expiration.yml
Labels: review-needed

#1752 Update impersonation_adobe_suspicious_language_link.yml
  detection-rules/impersonation_adobe_suspicious_language_link.yml
Labels: review-needed

#1747 Update link_google_presentation_open_redirect.yml
  detection-rules/link_google_presentation_open_redirect.yml
Labels: review-needed

#1754 Update spam_image_hidden_element.yml
  detection-rules/spam_image_hidden_element.yml
Labels: review-needed

#1750 Update spam_image_hidden_element.yml
  detection-rules/spam_image_hidden_element.yml
Labels: review-needed

#1745 Update impersonation_sharepoint_fake_file_share.yml
  detection-rules/impersonation_sharepoint_fake_file_share.yml
Labels: review-needed

#1758 Update body_callback_phishing_no_attachment.yml
  detection-rules/body_callback_phishing_no_attachment.yml
Labels: review-needed

#1759 Create current_event_crowdstrike.yml
  discovery-rules/current_event_crowdstrike.yml
Labels: review-needed

#1751 Update attachment_eml_cred_theft_language.yml
  detection-rules/attachment_eml_cred_theft_language.yml
Labels: review-needed

#1757 Update attachment_fake_attachment_image.yml
  detection-rules/attachment_fake_attachment_image.yml
Labels: review-needed

#1749 Update attachment_docusign_image_suspicious_links.yml
  detection-rules/attachment_docusign_image_suspicious_links.yml
Labels: review-needed

#1733 Create suspicious_sharepoint_file_shared.yml
  detection-rules/suspicious_sharepoint_file_shared.yml
Labels: in-test-rules, review-needed

#1766 CS Discovery Rule Update
  discovery-rules/current_event_crowdstrike.yml
Labels: review-needed

#1767 Update link_download_suspicious_file.yml
  detection-rules/link_download_suspicious_file.yml
Labels: review-needed

#1753 Update qr_code_suspicious_indicators.yml
  detection-rules/qr_code_suspicious_indicators.yml
Labels: review-needed

#1776 Update CS Discovery Rule - current_event_crowdstrike.yml
  discovery-rules/current_event_crowdstrike.yml
Labels: review-needed

#1729 Links - Multistage Abused Services
  detection-rules/link_multistage_adobe_express.yml
  detection-rules/link_multistage_docusign.yml
Labels: in-test-rules, review-needed

#1777 Updating callback rules
  detection-rules/attachment_callback_phish_via_text_file.yml
  detection-rules/callback_phishing_docusign_comment.yml
Labels: review-needed

#1778 Create attachment_pdf_malicious_creator_juliep.yml
  detection-rules/attachment_pdf_malicious_creator_juliep.yml
Labels: in-test-rules

#1779 Update body_bec_mobile_solicitation.yml
  detection-rules/body_bec_mobile_solicitation.yml
Labels: review-needed

#1755 Update attachment_qr_code_suspicious_components.yml
  detection-rules/attachment_qr_code_suspicious_components.yml
Labels: review-needed

#1770 Update link_fake_storage_alert.yml
  detection-rules/link_fake_storage_alert.yml
Labels: review-needed

#1768 Fixing "Encrypted attachments" to include zip
  insights/attachments/encrypted.yml
  insights/attachments/encrypted_zip_inside.yml
Labels: review-needed

#1785 Update link_content_credential_phishing.yml
  detection-rules/link_content_credential_phishing.yml
Labels: review-needed

#1772 Update Fake Threads logic
  detection-rules/fake_thread_suspicious_indicators.yml
  detection-rules/impersonation_fake_msg_thread_mismatched_from_freemail_replyto.yml
  detection-rules/vip_impersonation_fake_thread.yml
  insights/headers/fake_thread.yml
Labels: review-needed

#1783 Update attachment_callback_phish_with_pdf.yml
  detection-rules/attachment_callback_phish_with_pdf.yml
Labels: review-needed

#1797 Update google_drive_abuse_credential_phishing.yml
  detection-rules/google_drive_abuse_credential_phishing.yml
Labels: review-needed

#1746 Update link_microsoft_low_reputation.yml
  detection-rules/link_microsoft_low_reputation.yml
Labels: review-needed
