Repository sublime-security/sublime-rules, pull requests merged in 2024-08, with the labels that each got.

#1724 Update link_microsoft_low_reputation.yml
  detection-rules/link_microsoft_low_reputation.yml
Labels: review-needed

#1794 New Rule: Suspicious Attachment: Duplicate decoy PDF files
  detection-rules/suspicious_attachment_duplicate_decoy_pdf_attachments.yml
Labels: in-test-rules, review-needed

#1787 Update impersonation_twitter.yml
  detection-rules/impersonation_twitter.yml
Labels: review-needed

#1798 Update headers_replyto_new_domain_nlu_request.yml
  detection-rules/headers_replyto_new_domain_nlu_request.yml
Labels: review-needed

#1792 New Rule: Attachment: RTF file with suspicious link
  detection-rules/attachment_rtf_file_with_suspicious_link.yml
Labels: in-test-rules, review-needed

#1810 Update impersonation_zoom_strict.yml
  detection-rules/impersonation_zoom_strict.yml
Labels: review-needed

#1786 Update credential_phishing_corporate_services_impersonation_with_susp…
  detection-rules/credential_phishing_corporate_services_impersonation_with_suspicious_link.yml
Labels: review-needed

#1788 Update attachment_office365_image.yml
  detection-rules/attachment_office365_image.yml
Labels: review-needed

#1791 Update impersonation_docusign.yml
  detection-rules/impersonation_docusign.yml
Labels: review-needed

#1806 Updating callback rules
  detection-rules/body_callback_phishing_no_attachment.yml
  detection-rules/callback_phishing_nlu_body_or_attachments.yml
Labels: review-needed

#1756 Updating Fake Password Expiration from New and Unsolicited sender and Fake thread with suspicious indicators
  detection-rules/fake_thread_suspicious_indicators.yml
  detection-rules/link_fake_password_expiration.yml
Labels: review-needed

#1796 Update impersonation_dropbox.yml
  detection-rules/impersonation_dropbox.yml
Labels: review-needed

#1817 Adding mimecastprotect.com to Mimecast negations
  detection-rules/attachment_adobe_image_lure.yml
  detection-rules/spam_single_recipient_duplicated_in_cc.yml
  insights/links/mismatched.yml
Labels: review-needed

#1816 Update attachment_microsoft_image_lure_qr_code.yml
  detection-rules/attachment_microsoft_image_lure_qr_code.yml
Labels: review-needed

#1824 Update encrypted.yml
  insights/attachments/encrypted.yml
Labels: review-needed

#1826 Updating QR code insights to fire on Office documents
  insights/attachments/links_qr_code.yml
  insights/attachments/links_qr_contains_recipient_email.yml
  insights/attachments/links_qr_free_subdomain.yml
Labels: review-needed

#1821 Update impersonation_human_resources.yml
  detection-rules/impersonation_human_resources.yml
Labels: review-needed

#1819 Create attachment_extortion.yml
  detection-rules/attachment_extortion.yml
Labels: in-test-rules

#1789 Update body_extortion.yml
  detection-rules/body_extortion.yml
Labels: review-needed

#1830 Update attachment_pdf_malicious_creator_juliep.yml
  detection-rules/attachment_pdf_malicious_creator_juliep.yml
Labels: review-needed

#1814 New rule: Callback phishing via Intuit service abuse
  detection-rules/callback_phishing_intuit.yml
Labels: in-test-rules

#1773 Create impersonation_gmail_av_scan.yml
  detection-rules/attachment_fake_gmail_attachment.yml
Labels: in-test-rules, review-needed

#1818 Update attachment_docusign_image_suspicious_links.yml
  detection-rules/attachment_docusign_image_suspicious_links.yml
Labels: review-needed

#1800 Multiple Open Redirects
  detection-rules/open_redirect_bestdealstoday.yml
  detection-rules/open_redirect_chkc.yml
  detection-rules/open_redirect_clubos.yml
  detection-rules/open_redirect_documentmailbox.yml
  detection-rules/open_redirect_exactag.yml
  detection-rules/open_redirect_g7fr.yml
  detection-rules/open_redirect_indiatimes.yml
  detection-rules/open_redirect_isadatalab.yml
  detection-rules/open_redirect_learningapps.yml
  detection-rules/open_redirect_medium.yml
  detection-rules/open_redirect_premierbet.yml
  detection-rules/open_redirect_usthk.yml
Labels: in-test-rules, review-needed

#1842 Update spam_fake_photo_share.yml
  detection-rules/spam_fake_photo_share.yml
Labels: review-needed

#1845 Update spam_fake_photo_share.yml
  detection-rules/spam_fake_photo_share.yml
Labels: review-needed

#1805 Create open_redirect_artkaderne.yml
  detection-rules/open_redirect_artkaderne.yml
Labels: in-test-rules, review-needed

#1843 Update open_redirect_clubos.yml
  detection-rules/open_redirect_clubos.yml
Labels: review-needed

#1831 Update qr_code_suspicious_indicators.yml
  detection-rules/qr_code_suspicious_indicators.yml
Labels: review-needed

#1827 Update attachment_adobe_image_lure_qr_code.yml
  detection-rules/attachment_adobe_image_lure_qr_code.yml
Labels: in-test-rules, review-needed

#1847 Update impersonation_docusign.yml
  detection-rules/impersonation_docusign.yml
Labels: review-needed

#1825 Create attachment_encrypted_pdf_cred_theft.yml
  detection-rules/attachment_encrypted_pdf_cred_theft.yml
Labels: in-test-rules, review-needed

#1728 Create attachment_html_excessive_concatenation.yml
  detection-rules/attachment_html_excessive_concatenation.yml
Labels: in-test-rules, review-needed

#1801 Create brand_impersonation_stripe_notification.yml
  detection-rules/brand_impersonation_stripe_notification.yml
Labels: in-test-rules, review-needed

#1822 Create brand_impersonation_ms_planner.yml
  detection-rules/brand_impersonation_ms_planner.yml
Labels: in-test-rules, review-needed

#1837 Update link_credential_phishing_voicemail_language.yml
  detection-rules/link_credential_phishing_voicemail_language.yml
Labels: review-needed

#1859 Update spam_attendee_list_solicitation.yml
  detection-rules/spam_attendee_list_solicitation.yml
Labels: review-needed

#1860 Update impersonation_github.yml
  detection-rules/impersonation_github.yml
Labels: review-needed

#1861 Update link_sharepoint_sus_name.yml
  detection-rules/link_sharepoint_sus_name.yml
Labels: review-needed

#1862 Update attachment_html_smuggling_atob.yml
  detection-rules/attachment_html_smuggling_atob.yml
Labels: review-needed

#1863 Update credential_phishing_corporate_services_impersonation_with_suspicious_link.yml
  detection-rules/credential_phishing_corporate_services_impersonation_with_suspicious_link.yml
Labels: review-needed

#1858 Update body_bec_mobile_solicitation.yml
  detection-rules/body_bec_mobile_solicitation.yml
Labels: review-needed

#1864 Update link_credential_phishing_secure_message.yml
  detection-rules/link_credential_phishing_secure_message.yml
Labels: review-needed

#1865 Update spam_onmicrosoft.yml
  detection-rules/spam_onmicrosoft.yml
Labels: review-needed
