Repository sublime-security/sublime-rules, pull requests merged in 2024-09, with the labels that each got.

#1835 Create ms_infrastructure_abuse.yml
  detection-rules/ms_infrastructure_abuse.yml
Labels: in-test-rules

#1854 Update impersonation_docusign.yml
  detection-rules/impersonation_docusign.yml
Labels: review-needed

#1869 Update credential_phishing_corporate_services_impersonation_with_suspicious_link.yml
  detection-rules/credential_phishing_corporate_services_impersonation_with_suspicious_link.yml
Labels: review-needed

#1850 Update impersonation_sharepoint_fake_file_share.yml
  detection-rules/impersonation_sharepoint_fake_file_share.yml
Labels: review-needed

#1848 Update qr_code_suspicious_indicators.yml
  detection-rules/qr_code_suspicious_indicators.yml
Labels: review-needed

#1880 Update body_extortion.yml
  detection-rules/body_extortion.yml
Labels: review-needed

#1872 Create open_redirect_emp-eduyield.yml
  detection-rules/open_redirect_emp-eduyield.yml
Labels: in-test-rules, review-needed

#1829 Update paypal_invoice_abuse.yml
  detection-rules/paypal_invoice_abuse.yml
Labels: in-test-rules, review-needed

#1871 Update credential_phishing_esign_document_notification.yml
  detection-rules/credential_phishing_esign_document_notification.yml
Labels: review-needed

#1878 Update link_sharepoint_sus_name.yml
  detection-rules/link_sharepoint_sus_name.yml
Labels: review-needed

#1804 Create open_redirect_emlakarsa.yml
  detection-rules/open_redirect_emlakarsa.yml
Labels: in-test-rules, review-needed

#1808 Create open_redirect_pirlsandiego.yml
  detection-rules/open_redirect_pirlsandiego.yml
Labels: in-test-rules, review-needed

#1815 Create link_multistage_microsoft_forms.yml
  detection-rules/link_multistage_microsoft_forms.yml
Labels: in-test-rules, review-needed

#1888 Update body_extortion.yml
  detection-rules/body_extortion.yml
Labels: review-needed

#1886 Update link_sharepoint_sus_name.yml
  detection-rules/link_sharepoint_sus_name.yml
Labels: review-needed

#1856 Create bec_fraudulent_etailer.yml
  detection-rules/bec_fraudulent_etailer.yml
Labels: in-test-rules

#1889 Create open_redirect_tiktok.yml
  detection-rules/open_redirect_tiktok.yml
Labels: in-test-rules, review-needed

#1799 Create link_multistage_google_drive.yml
  detection-rules/link_multistage_google_drive.yml
Labels: in-test-rules, review-needed

#1838 Update spam_image_hidden_element.yml
  detection-rules/spam_image_hidden_element.yml
Labels: in-test-rules, review-needed

#1495 Create open_redirect_artisteer.yml
  detection-rules/open_redirect_artisteer.yml
Labels: in-test-rules, review-needed

#1114 New rule: open_redirect_newegg.yml
  detection-rules/open_redirect_newegg.yml
Labels: review-needed

#1515 Create open_redirect_sigtn.yml
  detection-rules/open_redirect_sigtn.yml
Labels: in-test-rules, review-needed

#1295 New rule (Open redirect): Dell
  detection-rules/open_redirect_dell.yml
Labels: in-test-rules, review-needed

#1367 New rule (Open redirect): City of Calgary
  detection-rules/open_redirect_calgary.yml
Labels: review-needed

#1873 Create open_redirect_secondstreet.yml
  detection-rules/open_redirect_secondstreet.yml
Labels: in-test-rules, review-needed

#1874 Create open_redirect_pmifunds.yml
  detection-rules/open_redirect_pmifunds.yml
Labels: in-test-rules, review-needed

#845 New Rule: open_redirect_indeed.yml
  detection-rules/open_redirect_indeed.yml
Labels: review-needed

#1868 Create brand_impersonation_docsend.yml
  detection-rules/brand_impersonation_docsend.yml
Labels: in-test-rules, review-needed

#1895 Update open_redirect_sigtn.yml
  detection-rules/open_redirect_sigtn.yml
Labels: review-needed

#1896 Update impersonation_amex.yml
  detection-rules/impersonation_amex.yml
Labels: review-needed

#1506 Create asr_suspicious_mailer_gmail.yml
  detection-rules/asr_suspicious_mailer_gmail.yml
Labels: review-needed

#1900 Update credential_phishing_fake_email_quarantine_notification.yml
  detection-rules/credential_phishing_fake_email_quarantine_notification.yml
Labels: review-needed

#1849 Create impersonation_mailgun.yml
  detection-rules/impersonation_mailgun.yml
Labels: in-test-rules, review-needed

#1902 Update link_fake_password_expiration.yml
  detection-rules/link_fake_password_expiration.yml
Labels: review-needed

#1903 Update link_credential_phishing_intent_and_other_indicators.yml
  detection-rules/link_credential_phishing_intent_and_other_indicators.yml
Labels: review-needed

#1904 sync sus subject usage
  detection-rules/attachment_eml_cred_theft.yml
  detection-rules/credential_phishing_suspicious_subject_nlu_financial_urgent.yml
  detection-rules/impersonation_wise.yml
  detection-rules/link_credential_phishing_intent_and_other_indicators.yml
  detection-rules/link_suspicious_message_unscannable_cloudflare.yml
  detection-rules/link_suspicious_subject_with_cyrillic_substitutions.yml
  detection-rules/qr_code_suspicious_indicators.yml
  detection-rules/salesforce_infra_abuse.yml
  insights/content/suspicious_subject.yml
Labels: review-needed

#1905 Update attachment_small_html_recipient_address.yml
  detection-rules/attachment_small_html_recipient_address.yml
Labels: review-needed

#1897 Update headers_replyto_new_domain_nlu_request.yml
  detection-rules/headers_replyto_new_domain_nlu_request.yml
Labels: review-needed

#1913 Update spam_attendee_list_solicitation.yml
  detection-rules/spam_attendee_list_solicitation.yml
Labels: review-needed

#1916 Update attachment_credential_phishing_secure_message.yml
  detection-rules/attachment_credential_phishing_secure_message.yml
Labels: review-needed

#1547 Create brand_impersonation_interac.yml
  detection-rules/brand_impersonation_interac.yml
Labels: review-needed

#1918 Update link_fake_storage_alert.yml
  detection-rules/link_fake_storage_alert.yml
Labels: review-needed

#1909 Update link_multistage_google_drive.yml
  detection-rules/link_multistage_google_drive.yml
Labels: review-needed

#1906 Update impersonation_sharepoint_fake_file_share.yml
  detection-rules/impersonation_sharepoint_fake_file_share.yml
Labels: review-needed

#1911 Update impersonation_wells_fargo.yml
  detection-rules/impersonation_wells_fargo.yml
Labels: review-needed

#1784 Create link_webflow_unsolicited.yml
  detection-rules/link_webflow_unsolicited.yml
Labels: in-test-rules, review-needed

#1876 Create open_redirect_eodcnetworkdirect.yml
  detection-rules/open_redirect_eodcnetworkdirect.yml
Labels: in-test-rules, review-needed

#1894 Update paypal_invoice_abuse.yml
  detection-rules/paypal_invoice_abuse.yml
Labels: in-test-rules, review-needed

#1907 Create open_redirect_phoenixartstudio.yml
  detection-rules/open_redirect_phoenixartstudio.yml
Labels: in-test-rules, review-needed

#1877 Create open_redirect_csiro-au.yml
  detection-rules/open_redirect_csiro-au.yml
Labels: in-test-rules, review-needed

#1596 Create brand_impersonation_enbridge.yml
  detection-rules/brand_impersonation_enbridge.yml
Labels: review-needed

#1921 Update attachment_disallowed_file_type_in_archive.yml
  detection-rules/attachment_disallowed_file_type_in_archive.yml
Labels: review-needed

#1908 Update link_microsoft_low_reputation.yml
  detection-rules/link_microsoft_low_reputation.yml
Labels: in-test-rules, review-needed

#1920 Update impersonation_mailgun.yml
  detection-rules/impersonation_mailgun.yml
Labels: review-needed

#1927 Update attachment_pdf_extortion_leveraging_breach_data.yml
  detection-rules/attachment_pdf_extortion_leveraging_breach_data.yml
Labels: review-needed

#1925 Update credential_phishing_fake_email_quarantine_notification.yml
  detection-rules/credential_phishing_fake_email_quarantine_notification.yml
Labels: review-needed

#1930 Update link_suspicious_lookerstudio_new_unsolicited_sender.yml
  detection-rules/link_suspicious_lookerstudio_new_unsolicited_sender.yml
Labels: review-needed

#1914 Update 2 Adobe rules
  detection-rules/attachment_adobe_image_lure.yml
  detection-rules/impersonation_adobe_suspicious_language_link.yml
Labels: review-needed

#1884 Update impersonation_aramco.yml
  detection-rules/impersonation_aramco.yml
Labels: review-needed

#1915 Update impersonation_dhl.yml
  detection-rules/impersonation_dhl.yml
Labels: review-needed

#1892 Update attachment_adobe_image_lure.yml
  detection-rules/attachment_adobe_image_lure.yml
Labels: review-needed

#1922 Update link_credential_phishing_voicemail_language.yml
  detection-rules/link_credential_phishing_voicemail_language.yml
Labels: in-test-rules, review-needed

#1879 Create link_sharepoint_folder_file.yml
  detection-rules/link_sharepoint_folder_file.yml
Labels: review-needed

#1948 Update sender_ad_distinguished_name.yml
  detection-rules/sender_ad_distinguished_name.yml
Labels: review-needed

#1949 Adding netflix.shop to trusted domains
  detection-rules/impersonation_netflix.yml
Labels: review-needed

#1946 Update attachment_eml_cred_theft_language.yml
  detection-rules/attachment_eml_cred_theft_language.yml
Labels: review-needed

#1937 Update link_fake_password_expiration.yml
  detection-rules/link_fake_password_expiration.yml
Labels: review-needed

#1912 Update credential_phishing_docusign_embedded_image_lure.yml
  detection-rules/credential_phishing_docusign_embedded_image_lure.yml
Labels: review-needed

#1934 Update spam_attendee_list_solicitation.yml
  detection-rules/spam_attendee_list_solicitation.yml
Labels: review-needed

#1951 Update impersonation_netflix.yml
  detection-rules/impersonation_netflix.yml
Labels: review-needed

#1931 Update spam_image_hidden_element.yml
  detection-rules/spam_image_hidden_element.yml
Labels: in-test-rules, review-needed

#1952 Update impersonation_facebook.yml
  detection-rules/impersonation_facebook.yml
Labels: review-needed

#1941 Update link_credential_phishing_intent_and_other_indicators.yml
  detection-rules/link_credential_phishing_intent_and_other_indicators.yml
Labels: review-needed

#1950 Update impersonation_dhl.yml
  detection-rules/impersonation_dhl.yml
Labels: review-needed

#1809 Create impersonation_stripe.yml
  detection-rules/impersonation_stripe.yml
Labels: in-test-rules, review-needed

#1959 Update attachment_extortion.yml
  detection-rules/attachment_extortion.yml
Labels: review-needed

#1293 Updating rules to use attack_types: Reconnaissance
  detection-rules/recon_large_recipients_unknown.yml
  detection-rules/recon_recipients_bccd_undisclosed.yml
Labels: help wanted
