Repository sublime-security/sublime-rules, pull requests merged in 2024-11, with the labels that each got.

#2068 Update impersonation_netflix.yml
  detection-rules/impersonation_netflix.yml
Labels: review-needed

#2056 Update attachment_callback_phish_with_img.yml
  detection-rules/attachment_callback_phish_with_img.yml
Labels: review-needed

#2062 Update link_credential_phishing_voicemail_language.yml
  detection-rules/link_credential_phishing_voicemail_language.yml
Labels: review-needed

#2064 Update paypal_invoice_abuse.yml
  detection-rules/paypal_invoice_abuse.yml
Labels: review-needed

#2031 Update body_advance_fee_new_sender.yml
  detection-rules/body_advance_fee_new_sender.yml
Labels: review-needed

#2050 Update callback_phishing_nlu_body_or_attachments.yml
  detection-rules/callback_phishing_nlu_body_or_attachments.yml
Labels: in-test-rules, review-needed

#2083 Update brand_impersonation_hulu.yml
  detection-rules/brand_impersonation_hulu.yml
Labels: review-needed

#2063 Create abused_payoneer_callback.yml
  detection-rules/abused_payoneer_callback.yml
Labels: in-test-rules, review-needed

#2084 Update link_multistage_adobe_express.yml
  detection-rules/link_multistage_adobe_express.yml
Labels: review-needed

#2080 Update credential_phishing_corporate_services_impersonation_with_susp…
  detection-rules/credential_phishing_corporate_services_impersonation_with_suspicious_link.yml
Labels: review-needed

#1960 Create link_multistage_frame_io.yml
  detection-rules/link_multistage_frame_io.yml
Labels: review-needed

#1940 Create link_zoho_forms_unsolicited.yml
  detection-rules/link_zoho_forms_unsolicited.yml
Labels: in-test-rules, review-needed

#2044 Create abuse_docusign_unsolicited_reply-to.yml
  detection-rules/abuse_docusign_unsolicited_reply-to.yml
Labels: in-test-rules, review-needed

#2075 Create links_attached_emls.yml
  insights/attachments/links_attached_eml.yml
  insights/attachments/links_domains_attached_eml.yml
  insights/attachments/links_free_file_host_attached_eml.yml
  insights/attachments/links_free_subdomain_host_attached_eml.yml
  insights/attachments/links_low_reputation_attached_eml.yml
  insights/attachments/links_qr_code_attached_eml.yml
  insights/attachments/links_qr_contains_recipient_email_attached_eml.yml
  insights/attachments/links_qr_free_subdomain_attached_eml.yml
  insights/attachments/links_recipient_email_attached_emls.yml
  insights/attachments/links_url_shortner_attached_eml.yml
Labels: review-needed

#2097 Update abuse_docusign_unsolicited_reply-to.yml
  detection-rules/abuse_docusign_unsolicited_reply-to.yml
Labels: review-needed

#2093 Update link_credential_phishing_voicemail_language.yml
  detection-rules/link_credential_phishing_voicemail_language.yml
Labels: review-needed

#2096 Update link_credential_phishing_voicemail_language.yml
  detection-rules/link_credential_phishing_voicemail_language.yml
Labels: review-needed

#2118 Revert "Delete detection-rules/shopify_infra_abuse.yml"
  detection-rules/shopify_infra_abuse.yml
Labels: review-needed

#2106 Update impersonation_microsoft_credential_theft.yml
  detection-rules/impersonation_microsoft_credential_theft.yml
Labels: in-test-rules, review-needed

#2108 Update sender_ad_distinguished_name.yml
  detection-rules/sender_ad_distinguished_name.yml
Labels: review-needed

#2100 Update link_google_open_redirect_with_suspicious_indicators.yml
  detection-rules/link_google_open_redirect_with_suspicious_indicators.yml
Labels: review-needed

#2111 Update impersonation_sharepoint_fake_file_share.yml
  detection-rules/impersonation_sharepoint_fake_file_share.yml
Labels: review-needed

#2105 Update attachment_eml_cred_theft_language.yml
  detection-rules/attachment_eml_cred_theft_language.yml
Labels: review-needed

#2082 Update credential_phishing_esign_document_notification.yml
  detection-rules/credential_phishing_esign_document_notification.yml
Labels: in-test-rules

#2112 Update credential_phishing_esign_document_notification.yml
  detection-rules/credential_phishing_esign_document_notification.yml
Labels: review-needed

#2101 Update impersonation_quickbooks.yml
  detection-rules/impersonation_quickbooks.yml
Labels: review-needed

#2113 Update link_google_share_notificaiton_sus_comments.yml
  detection-rules/link_google_share_notificaiton_sus_comments.yml
Labels: review-needed

#2116 Update impersonation_usps.yml
  detection-rules/impersonation_usps.yml
Labels: review-needed

#2109 Update impersonation_dropbox.yml
  detection-rules/impersonation_dropbox.yml
Labels: review-needed

#2117 Update impersonation_quickbooks.yml
  detection-rules/impersonation_quickbooks.yml
Labels: review-needed

#2094 Create abuse_docusign_sus_names.yml
  detection-rules/abuse_docusign_sus_names.yml
Labels: in-test-rules, review-needed

#2114 Update callback_phishing_intuit.yml
  detection-rules/callback_phishing_intuit.yml
Labels: review-needed

#2115 Update link_credential_phishing_intent_and_other_indicators.yml
  detection-rules/link_credential_phishing_intent_and_other_indicators.yml
Labels: review-needed

#2104 Update impersonation_mailgun.yml
  detection-rules/impersonation_mailgun.yml
Labels: review-needed

#2103 Update impersonation_facebook.yml
  detection-rules/impersonation_facebook.yml
Labels: review-needed

#2099 Update impersonation_sharepoint_body_credential_theft.yml
  detection-rules/impersonation_sharepoint_body_credential_theft.yml
Labels: review-needed

#2029 Create link_adobe_share_suspicious.yml
  detection-rules/link_adobe_share_suspicious.yml
Labels: review-needed

#2076 Create abuse_dropbox_new_domain.yml
  detection-rules/abuse_dropbox_new_domain.yml
Labels: in-test-rules, review-needed

#2091 Update attachment_docusign_suspicious_links.yml
  detection-rules/attachment_docusign_suspicious_links.yml
Labels: review-needed

#2089 Update link_credential_phishing_intent_and_other_indicators.yml
  detection-rules/link_credential_phishing_intent_and_other_indicators.yml
Labels: review-needed

#2081 Create open_redirect_slubnaglowie.yml
  detection-rules/open_redirect_slubnaglowie.yml
Labels: review-needed

#2125 Update body_extortion.yml
  detection-rules/body_extortion.yml
Labels: review-needed

#2021 Create suspicious_request_financial.yml
  detection-rules/suspicious_request_financial.yml
Labels: in-test-rules, review-needed

#2086 Update link_dynamics_form.yml
  detection-rules/link_dynamics_form.yml
Labels: review-needed

#2026 Create francais_business_email_compromise_new_sender.yml
  detection-rules/francais_business_email_compromise_new_sender.yml
Labels: in-test-rules, review-needed

#2124 Update impersonation_mailgun.yml
  detection-rules/impersonation_mailgun.yml
Labels: review-needed

#2123 Update impersonation_netflix.yml
  detection-rules/impersonation_netflix.yml
Labels: review-needed

#2121 Update hr_impersonation_docusign_comment.yml
  detection-rules/hr_impersonation_docusign_comment.yml
Labels: review-needed

#2129 Create icloud_private_relay.yml
  insights/sender/icloud_private_relay.yml
Labels: review-needed

#2027 Create attachment_eml_suspicious_indicators.yml
  detection-rules/attachment_eml_suspicious_indicators.yml
Labels: in-test-rules, review-needed

#2140 New rule: VIP local_part impersonation from unsolicited sender
  detection-rules/vip_impersonation_local_part.yml
Labels: in-test-rules

#2127 Update link_credential_phishing_intent_and_other_indicators.yml
  detection-rules/link_credential_phishing_intent_and_other_indicators.yml
Labels: review-needed

#2102 Update impersonation_quickbooks.yml
  detection-rules/impersonation_quickbooks.yml
Labels: review-needed

#2128 Update credential_phishing_esign_document_notification.yml
  detection-rules/credential_phishing_esign_document_notification.yml
Labels: review-needed

#2126 Update spam_fake_photo_share.yml
  detection-rules/spam_fake_photo_share.yml
Labels: review-needed

#2145 Create attachment_ics_file_non_rfc_compliant.yml
  detection-rules/attachment_ics_file_non_rfc_compliant.yml
Labels: review-needed

#2146 Update qr_code_suspicious_indicators.yml
  detection-rules/qr_code_suspicious_indicators.yml
Labels: review-needed

#2148 Update attachment_docusign_suspicious_links.yml
  detection-rules/attachment_docusign_suspicious_links.yml
Labels: review-needed

#2149 Update link_credential_phishing_intent_and_other_indicators.yml
  detection-rules/link_credential_phishing_intent_and_other_indicators.yml
Labels: review-needed

#2156 Create new_account_verification_code.yml
  discovery-rules/new_account_verification_code.yml
Labels: discovery-rule

#2155 Update attachment_docusign_suspicious_links.yml
  detection-rules/attachment_docusign_suspicious_links.yml
Labels: review-needed

#2079 Create brand_impersonation_knowbe4.yml
  detection-rules/brand_impersonation_knowbe4.yml
Labels: in-test-rules, review-needed

#2119 Update link_credential_phishing_intent_and_other_indicators.yml
  detection-rules/link_credential_phishing_intent_and_other_indicators.yml
Labels: review-needed

#2143 Update link_suspicious_message_unscannable_cloudflare.yml
  detection-rules/link_suspicious_message_unscannable_cloudflare.yml
Labels: review-needed

#2158 Update link_credential_phishing_voicemail_language.yml
  detection-rules/link_credential_phishing_voicemail_language.yml
Labels: review-needed

#2144 Create impersonation_schwab.yml
  detection-rules/impersonation_schwab.yml
Labels: in-test-rules, review-needed

#2169 Create malformed_ole_header rule and yara
  detection-rules/attachment_malformed_ole.yml
  yara/malformed_ole_header.yar
Labels: review-needed

#2173 Update brand_impersonation_hulu.yml
  detection-rules/brand_impersonation_hulu.yml
Labels: review-needed

#2122 Update impersonation_ledger.yml
  detection-rules/impersonation_ledger.yml
Labels: review-needed

#2174 Update spam_attendee_list_solicitation.yml
  detection-rules/spam_attendee_list_solicitation.yml
Labels: in-test-rules, review-needed

#2176 Update impersonation_dhl.yml
  detection-rules/impersonation_dhl.yml
Labels: review-needed

#2171 Update body_job_scam_unsolicited.yml
  detection-rules/body_job_scam_unsolicited.yml
Labels: review-needed
