Repository sublime-security/sublime-rules, pull requests merged in 2025-04, with the labels that each got.

#2536 Update attachment_small_html_recipient_address.yml
  detection-rules/attachment_small_html_recipient_address.yml
Labels: review-needed

#2473 Update impersonation_quickbooks.yml
  detection-rules/impersonation_quickbooks.yml
Labels: in-test-rules, review-needed

#2513 Create link_squarespace_abuse.yml
  detection-rules/link_squarespace_abuse.yml
Labels: in-test-rules, review-needed

#2523 Create canva_infra_abuse.yml
  detection-rules/canva_infra_abuse.yml
Labels: in-test-rules, review-needed

#2543 Update impersonation_human_resources.yml
  detection-rules/impersonation_human_resources.yml
Labels: review-needed

#2538 Create open_redirect_whitefox.yml
  detection-rules/open_redirect_whitefox.yml
Labels: in-test-rules, review-needed

#2520 Create attachment_html_suspicious_comments.yml
  detection-rules/attachment_html_suspicious_comments.yml
Labels: in-test-rules, review-needed

#2534 Create comp_review_qr_attached_eml.yml
  detection-rules/comp_review_qr_attached_eml.yml
Labels: in-test-rules, review-needed

#2471 Update credential_phishing_corporate_services_impersonation_with_susp…
  detection-rules/credential_phishing_corporate_services_impersonation_with_suspicious_link.yml
Labels: in-test-rules, review-needed

#2547 Update body_bec_mobile_solicitation.yml
  detection-rules/body_bec_mobile_solicitation.yml
Labels: review-needed

#2541 Update suspicious_request_for_quote_or_purchase.yml
  detection-rules/suspicious_request_for_quote_or_purchase.yml
Labels: review-needed

#2499 Create brand_impersonation_navan.yml
  detection-rules/brand_impersonation_navan.yml
Labels: review-needed

#2537 Create impersonation_docusign_via_cloudhq.yml
  detection-rules/impersonation_docusign_via_cloudhq.yml
Labels: in-test-rules

#2552 Update link_credential_phishing_intent_and_other_indicators.yml
  detection-rules/link_credential_phishing_intent_and_other_indicators.yml
Labels: review-needed

#2516 Create brand_impersonation_irs.yml
  detection-rules/brand_impersonation_irs.yml
Labels: in-test-rules, review-needed

#2556 Update impersonation_meta.yml
  detection-rules/impersonation_meta.yml
Labels: review-needed

#2515 Update link_credential_phishing_intent_and_other_indicators.yml
  detection-rules/link_credential_phishing_intent_and_other_indicators.yml
Labels: review-needed

#2560 Update link_google_share_notificaiton_sus_comments.yml
  detection-rules/link_google_share_notificaiton_sus_comments.yml
Labels: review-needed

#2542 Update impersonation_meta.yml
  detection-rules/impersonation_meta.yml
Labels: in-test-rules, review-needed

#2550 Update link_multistage_microsoft_forms.yml
  detection-rules/link_multistage_microsoft_forms.yml
Labels: in-test-rules, review-needed

#2564 Update impersonation_ups.yml
  detection-rules/impersonation_ups.yml
Labels: review-needed

#2570 Update link_credential_phishing_voicemail_language.yml
  detection-rules/link_credential_phishing_voicemail_language.yml
Labels: review-needed

#2573 Update link_microsoft_low_reputation.yml
  detection-rules/link_microsoft_low_reputation.yml
Labels: review-needed

#2574 Update impersonation_paypal.yml
  detection-rules/impersonation_paypal.yml
Labels: review-needed

#2569 Adding attachment size limit
  detection-rules/attachment_html_recipient_in_javascript_identifiers.yml
Labels: review-needed

#2578 Update brand_impersonation_booking_com.yml
  detection-rules/brand_impersonation_booking_com.yml
Labels: review-needed

#2568 Update impersonation_meta.yml
  detection-rules/impersonation_meta.yml
Labels: review-needed

#2572 Update impersonation_stripe.yml
  detection-rules/impersonation_stripe.yml
Labels: review-needed

#2571 Update link_credential_phishing_voicemail_language.yml
  detection-rules/link_credential_phishing_voicemail_language.yml
Labels: review-needed

#2575 Update attachment_adobe_image_lure.yml
  detection-rules/attachment_adobe_image_lure.yml
Labels: in-test-rules

#2553 convert to reply-to profiles
  detection-rules/abuse_docsend_unsolicited_reply-to.yml
  detection-rules/abuse_docusign_sus_names.yml
  detection-rules/abuse_docusign_unsolicited_reply-to.yml
  detection-rules/abuse_dropbox_new_domain.yml
  detection-rules/abuse_dropbox_unsolicited_reply-to.yml
  detection-rules/abuse_google_drive_unsolicited_reply-to.yml
  detection-rules/abuse_quickbooks_new_domain.yml
  detection-rules/docusign_new_sender_domain.yml
  detection-rules/headers_replyto_new_domain_nlu_request.yml
  detection-rules/link_multistage_docusign.yml
  detection-rules/link_multistage_google_drive.yml
  detection-rules/link_secure_sharepoint_file.yml
  detection-rules/suspicious_sharepoint_file_shared.yml
Labels: review-needed

#2576 Update brand_impersonation_vanguard.yml
  detection-rules/brand_impersonation_vanguard.yml
Labels: review-needed

#2589 Update link_suspicious_message_unscannable_cloudflare.yml
  detection-rules/link_suspicious_message_unscannable_cloudflare.yml
Labels: review-needed

#2585 Update scam_piano.yml
  detection-rules/scam_piano.yml
Labels: review-needed

#2582 Update credential_phishing_corporate_services_impersonation_with_susp…
  detection-rules/credential_phishing_corporate_services_impersonation_with_suspicious_link.yml
Labels: review-needed

#2583 Update link_credential_phishing_intent_and_other_indicators.yml
  detection-rules/link_credential_phishing_intent_and_other_indicators.yml
Labels: review-needed

#2577 Update body_advance_fee_new_sender.yml
  detection-rules/body_advance_fee_new_sender.yml
Labels: review-needed

#2580 Update link_fake_storage_alert.yml
  detection-rules/link_fake_storage_alert.yml
Labels: review-needed

#2596 Create link_wordpress_credphish.yml
  detection-rules/link_wordpress_credphish.yml
Labels: review-needed

#2566 Update attachment_fake_attachment_image.yml
  detection-rules/attachment_fake_attachment_image.yml
Labels: in-test-rules

#2592 Update link_credential_phishing_voicemail_language.yml
  detection-rules/link_credential_phishing_voicemail_language.yml
Labels: review-needed

#2593 Update attachment_qr_code_suspicious_components.yml
  detection-rules/attachment_qr_code_suspicious_components.yml
Labels: review-needed

#2594 Update link_qr_code_in_img_or_pdf_with_phishing_disposition.yml
  detection-rules/link_qr_code_in_img_or_pdf_with_phishing_disposition.yml
Labels: review-needed

#2595 Update link_qr_code_suspicious_language_fts.yml
  detection-rules/link_qr_code_suspicious_language_fts.yml
Labels: review-needed

#2597 Update link_credential_phishing.yml
  detection-rules/link_credential_phishing.yml
Labels: review-needed

#2584 Update impersonation_human_resources.yml
  detection-rules/impersonation_human_resources.yml
Labels: review-needed

#2587 Create callback_phishing_calendar_invite.yml
  detection-rules/callback_phishing_calendar_invite.yml
Labels: in-test-rules, review-needed

#2599 Update link_credential_phishing_voicemail_language.yml
  detection-rules/link_credential_phishing_voicemail_language.yml
Labels: review-needed

#2603 Update brand_impersonation_sendgrid.yml
  detection-rules/brand_impersonation_sendgrid.yml
Labels: review-needed

#2591 Update impersonation_microsoft_credential_theft.yml
  detection-rules/impersonation_microsoft_credential_theft.yml
Labels: review-needed

#2567 Update link_multistage_microsoft_forms.yml
  detection-rules/link_multistage_microsoft_forms.yml
Labels: review-needed

#2563 Create generic_service_abuse_reply_to.yml
  detection-rules/generic_service_abuse_reply_to.yml
Labels: in-test-rules, review-needed

#2581 Update link_fake_fax_low_reputation.yml
  detection-rules/link_fake_fax_low_reputation.yml
Labels: in-test-rules, review-needed

#2598 Update attachment_microsoft_image_lure_qr_code.yml
  detection-rules/attachment_microsoft_image_lure_qr_code.yml
Labels: in-test-rules

#2606 Update generic_service_abuse_reply_to.yml
  detection-rules/generic_service_abuse_reply_to.yml
Labels: review-needed

#2612 Create abuse_google_account_notification.yml
  detection-rules/abuse_google_account_notification.yml
Labels: review-needed

#2588 Update spam_fake_photo_share.yml
  detection-rules/spam_fake_photo_share.yml
Labels: in-test-rules

#2613 Update brand_impersonation_booking_com.yml
  detection-rules/brand_impersonation_booking_com.yml
Labels: review-needed

#2614 Update impersonation_netflix.yml
  detection-rules/impersonation_netflix.yml
Labels: review-needed

#2621 Update attachment_svg_embedded_js.yml
  detection-rules/attachment_svg_embedded_js.yml
Labels: review-needed

#2624 Update attachment_eml_svg_js.yml
  detection-rules/attachment_eml_svg_js.yml
Labels: review-needed

#2625 Update attachment_file_scheme_link_to_executable_filetype.yml
  detection-rules/attachment_file_scheme_link_to_executable_filetype.yml
Labels: review-needed

#2615 Update impersonation_amazon.yml
  detection-rules/impersonation_amazon.yml
Labels: review-needed

#2620 Update attachment_eml_suspicious_indicators.yml
  detection-rules/attachment_eml_suspicious_indicators.yml
Labels: review-needed

#2559 Create abuse_surveymonkey_new_domain.yml
  detection-rules/abuse_surveymonkey_new_domain.yml
Labels: in-test-rules, review-needed

#2632 Update spam_attendee_list_solicitation.yml
  detection-rules/spam_attendee_list_solicitation.yml
Labels: review-needed

#2618 Update link_credential_phishing_voicemail_language.yml
  detection-rules/link_credential_phishing_voicemail_language.yml
Labels: review-needed

#2644 Update impersonation_chase.yml
  detection-rules/impersonation_chase.yml
Labels: review-needed

#2649 removing inline sample references
  detection-rules/impersonation_mailgun.yml
  detection-rules/link_credential_phishing_voicemail_language.yml
  detection-rules/link_fake_fax_low_reputation.yml
  detection-rules/link_google_presentation_open_redirect.yml
Labels: review-needed

#2610 Update callback_phishing_adobesign.yml
  detection-rules/callback_phishing_adobesign.yml
Labels: review-needed

#2653 remove additional inline links
  detection-rules/link_fake_fax_low_reputation.yml
Labels: review-needed

#2630 Create callback_phishing_xodosign.yml
  detection-rules/callback_phishing_xodosign.yml
Labels: review-needed

#2636 Update link_multistage_adobe_acrobat_hosted_pdf.yml
  detection-rules/link_multistage_adobe_acrobat_hosted_pdf.yml
Labels: review-needed

#2637 Update open_redirect_adnxs.yml
  detection-rules/open_redirect_adnxs.yml
Labels: review-needed

#2641 Create brand_impersonation_aliexpress.yml
  detection-rules/brand_impersonation_aliexpress.yml
Labels: in-test-rules, review-needed

#2617 Updating suspicious comment rule
  detection-rules/attachment_web_suspicious_comments.yml
Labels: in-test-rules

#2635 Create open_redirect_business_google.yml
  detection-rules/open_redirect_business_google.yml
Labels: in-test-rules, review-needed

#2557 Update salesforce_infra_abuse.yml
  detection-rules/salesforce_infra_abuse.yml
Labels: review-needed

#2650 Create callback_aol_senders.yml
  detection-rules/callback_aol_senders.yml
Labels: in-test-rules, review-needed

#2548 Create abuse_hellosign_unsolicited_sender.yml
  detection-rules/abuse_hellosign_unsolicited_sender.yml
Labels: in-test-rules, review-needed

#2611 Create abuse_adobe_sign_unsolicited_reply-to.yml
  detection-rules/abuse_adobe_sign_unsolicited_reply-to.yml
Labels: review-needed

#2631 Update credential_phishing_corporate_services_impersonation_with_susp…
  detection-rules/credential_phishing_corporate_services_impersonation_with_suspicious_link.yml
Labels: review-needed

#2633 Create link_gammaapp_present.yml
  detection-rules/link_gammaapp_present.yml
Labels: in-test-rules, review-needed

#2656 Update link_credential_phishing.yml
  detection-rules/link_credential_phishing.yml
Labels: review-needed
