Repository sublime-security/sublime-rules, pull requests merged in 2025-06, with the labels that each got.

#2768 Update link_credential_phishing_intent_and_other_indicators.yml
  detection-rules/link_credential_phishing_intent_and_other_indicators.yml
Labels: review-needed

#2750 Update impersonation_sharepoint_fake_file_share.yml
  detection-rules/impersonation_sharepoint_fake_file_share.yml
Labels: review-needed

#2738 Create attachment_suspicious_message_unscannable_cloudflare.yml
  detection-rules/attachment_suspicious_message_unscannable_cloudflare.yml
Labels: review-needed

#2758 Create attachment_html_smuggling_eval_atob_calendar.yml
  detection-rules/attachment_html_smuggling_atob_ics.yml
  detection-rules/attachment_html_smuggling_eval_atob_calendar.yml
Labels: review-needed

#2761 Update recon_recipients_bccd_undisclosed.yml
  detection-rules/recon_recipients_bccd_undisclosed.yml
Labels: review-needed

#2690 Update impersonation_adobe_suspicious_language_link.yml
  detection-rules/impersonation_adobe_suspicious_language_link.yml
Labels: in-test-rules, review-needed

#2759 Update credential_phishing_one_drive_impersonation.yml
  detection-rules/credential_phishing_one_drive_impersonation.yml
Labels: in-test-rules, review-needed

#2778 Update link_suspicious_message_unscannable_cloudflare.yml
  detection-rules/link_suspicious_message_unscannable_cloudflare.yml
Labels: review-needed

#2744 Update govdelivery_compromise.yml
  detection-rules/govdelivery_compromise.yml
Labels: review-needed

#2793 Update link_secure_sharepoint_file.yml
  detection-rules/link_secure_sharepoint_file.yml
Labels: review-needed

#2687 Create attachment_legal_pdf_link.yml
  detection-rules/attachment_legal_pdf_link.yml
Labels: review-needed, hunting-required

#2786 Update link_credential_phishing_secure_message.yml
  detection-rules/link_credential_phishing_secure_message.yml
Labels: review-needed

#2790 Add credential phishing rule for email delivery failure impersonation
  detection-rules/credential_phishing_email_delivery_failure_impersonation.yml
Labels: in-test-rules

#2811 Update impersonation_github.yml
  detection-rules/impersonation_github.yml
Labels: review-needed

#2810 Update impersonation_twitter.yml
  detection-rules/impersonation_twitter.yml
Labels: review-needed

#2812 Update impersonation_venmo.yml
  detection-rules/impersonation_venmo.yml
Labels: review-needed

#2813 Extending root domains in impersonation_microsoft
  detection-rules/impersonation_microsoft.yml
Labels: review-needed

#2804 Create insight for vip
  insights/sender/sender_contains_org_vip.yml
Labels: review-needed

#2785 Modifying Callback Phish alert to tune out FPs caused by resume.
  detection-rules/attachment_callback_phish_with_pdf.yml
Labels: review-needed

#2827 Update attachment_python_pdf_link.yml
  discovery-rules/attachment_python_pdf_link.yml
Labels: review-needed

#2831 Update asr_suspicious_mailer_gmail.yml
  detection-rules/asr_suspicious_mailer_gmail.yml
Labels: review-needed

#2828 Updating logic to match on the sender_email
  detection-rules/link_webflow_unsolicited.yml
Labels: review-needed

#2836 Update link_content_credential_phishing.yml
  detection-rules/link_content_credential_phishing.yml
Labels: review-needed

#2840 Update impersonation_fedex.yml
  detection-rules/impersonation_fedex.yml
Labels: review-needed

#2843 Update impersonation_meta.yml
  detection-rules/impersonation_meta.yml
Labels: review-needed

#2846 Update impersonation_meta.yml
  detection-rules/impersonation_meta.yml
Labels: review-needed

#2832 Create attachment_soda_pdf_encrypt.yml
  detection-rules/attachment_soda_pdf_encrypt.yml
Labels: in-test-rules, review-needed

#2851 Update impersonation_meta.yml
  detection-rules/impersonation_meta.yml
Labels: review-needed

#2787 Update attachment_callback_phish_via_text_file.yml
  detection-rules/attachment_callback_phish_via_text_file.yml
Labels: in-test-rules, review-needed

#2857 Update attachment_sus_pdf_chrome.yml
  detection-rules/attachment_sus_pdf_chrome.yml
Labels: review-needed

#2859 Updating nlu cred theft alert to allow one bcc
  detection-rules/recipients_undisclosed_nlu_cred_theft_low_rep_links.yml
Labels: review-needed

#2865 Update credential_phishing_esign_document_notification.yml
  detection-rules/credential_phishing_esign_document_notification.yml
Labels: review-needed

#2863 Update fake_tax_prep_request.yml
  detection-rules/fake_tax_prep_request.yml
Labels: review-needed

#2875 Update link_fake_password_expiration.yml
  detection-rules/link_fake_password_expiration.yml
Labels: review-needed
