Repository sublime-security/sublime-rules, pull requests merged in 2025-07, with the labels that each got.

#2794 Create link_sharepoint_filename_org.yml
  detection-rules/link_sharepoint_filename_org.yml
  detection-rules/link_sharepoint_sus_name.yml
Labels: in-test-rules, review-needed

#2852 Update abuse_quickbooks_suspicious_comments.yml
  detection-rules/abuse_quickbooks_suspicious_comments.yml
Labels: in-test-rules, review-needed

#2869 Create link_rpmsg_self_addressed.yml
  detection-rules/link_rpmsg_self_addressed.yml
Labels: in-test-rules, review-needed

#2796 Create sharepoint_opt_filename_org.yml
  detection-rules/sharepoint_opt_filename_org.yml
Labels: in-test-rules, review-needed

#2871 Update spam_fake_photo_share.yml
  detection-rules/spam_fake_photo_share.yml
Labels: in-test-rules

#2884 Update link_notion_file_share.yml
  detection-rules/link_notion_file_share.yml
Labels: review-needed

#2885 BI Meta: Convert display name list to regex.icontains
  detection-rules/impersonation_meta.yml
Labels: review-needed

#2891 Create open_redirect_tuttocauzioni.yml
  detection-rules/open_redirect_tuttocauzioni.yml
Labels: review-needed

#2665 Create asr_new_sender_or_reply_to_with_new_linked_dom.yml
  detection-rules/asr_new_sender_or_reply_to_with_new_linked_dom.yml
Labels: in-test-rules

#2880 Updating zoom abuse detection
  detection-rules/abuse_zoom_docs_unsolicited_sender.yml
Labels: review-needed

#2897 Negating replies to DocuSign notifications
  detection-rules/attachment_docusign_suspicious_links.yml
Labels: review-needed

#2820 Create link_catbox.yml
  detection-rules/link_catbox.yml
Labels: in-test-rules, review-needed

#2899 Update impersonation_adobe_suspicious_language_link.yml
  detection-rules/impersonation_adobe_suspicious_language_link.yml
Labels: review-needed

#2874 Update credential_phishing_suspicious_subject_nlu_financial_urgent.yml
  detection-rules/credential_phishing_suspicious_subject_nlu_financial_urgent.yml
Labels: review-needed

#2919 Update link_multistage_microsoft_forms.yml
  detection-rules/link_multistage_microsoft_forms.yml
Labels: review-needed

#2927 Update credential_phishing_corporate_services_impersonation
  detection-rules/credential_phishing_corporate_services_impersonation_with_suspicious_link.yml
Labels: review-needed

#2931 Update link_fake_fax_low_reputation.yml
  detection-rules/link_fake_fax_low_reputation.yml
Labels: review-needed

#2932 Add voice note pattern to fake voicemail rule
  detection-rules/link_credential_phishing_voicemail_language.yml
Labels: review-needed, claude-code

#2921 Update body_job_scam_unsolicited.yml
  detection-rules/body_job_scam_unsolicited.yml
Labels: review-needed

#2896 Negate direct-to-VIP messages
  detection-rules/vip_impersonation_subject.yml
Labels: review-needed

#2944 Update credential_phishing_corporate_services_impersonation
  detection-rules/credential_phishing_corporate_services_impersonation_with_suspicious_link.yml
Labels: review-needed

#2941 Update link_fake_password_expiration.yml
  detection-rules/link_fake_password_expiration.yml
Labels: in-test-rules

#2942 Update suspicious_request_for_quote_or_purchase.yml
  detection-rules/suspicious_request_for_quote_or_purchase.yml
Labels: review-needed

#2945 Update spam_attendee_list_solicitation.yml
  detection-rules/spam_attendee_list_solicitation.yml
Labels: review-needed

#2940 Update brand_impersonation_ms_planner.yml
  detection-rules/brand_impersonation_ms_planner.yml
Labels: review-needed

#2943 Update credential_phishing_corporate_services_impersonation
  detection-rules/credential_phishing_corporate_services_impersonation_with_suspicious_link.yml
Labels: review-needed

#2939 Update impersonation_quickbooks.yml
  detection-rules/impersonation_quickbooks.yml
Labels: review-needed

#2870 Create link_sharepoint_sender_display_name.yml
  detection-rules/link_sharepoint_sender_display_name.yml
Labels: in-test-rules, review-needed

#2947 Update impersonation_twitter.yml
  detection-rules/impersonation_twitter.yml
Labels: review-needed

#2948 Update impersonation_chase.yml
  detection-rules/impersonation_chase.yml
Labels: review-needed

#2961 Update abuse_zoom_docs_unsolicited_sender.yml
  detection-rules/abuse_zoom_docs_unsolicited_sender.yml
Labels: review-needed

#2971 Update Zoom brand impersonation rule to exclude Notion domains
  detection-rules/brand_impersonation_zoom.yml
Labels: review-needed

#2973 Update callback_phishing_docusign_comment.yml
  detection-rules/callback_phishing_docusign_comment.yml
Labels: review-needed

#2783 Adding social landing check where URL shortener checks exist
  detection-rules/attachment_qr_code_suspicious_components.yml
  detection-rules/attachment_rtf_file_with_suspicious_link.yml
  detection-rules/brand_impersonation_ms_planner.yml
  detection-rules/credential_phishing_corporate_services_impersonation_with_suspicious_link.yml
  detection-rules/govdelivery_compromise.yml
  detection-rules/link_autodownloaded_html_smuggling.yml
  detection-rules/link_coinbase_low_rep_or_shortened.yml
  detection-rules/link_credential_phishing_intent_and_other_indicators.yml
  detection-rules/link_google_presentation_open_redirect.yml
  detection-rules/link_microsoft_low_reputation.yml
  detection-rules/link_multistage_adobe_express.yml
  detection-rules/link_multistage_docusign.yml
  detection-rules/link_multistage_frame_io.yml
  detection-rules/link_multistage_google_drive.yml
  detection-rules/link_published_google_doc.yml
  detection-rules/link_quickbooks_image_lure_suspicious_link.yml
  detection-rules/spam_url_shortener_emojis.yml
  detection-rules/spoofable_internal_domain_suspicious_signals.yml
Labels: review-needed

#2978 Update brand_impersonation_stripe_notification.yml
  detection-rules/brand_impersonation_stripe_notification.yml
Labels: review-needed

#2981 Update impersonation_usps.yml
  detection-rules/impersonation_usps.yml
Labels: review-needed

#2984 Update impersonation_coinbase.yml
  detection-rules/impersonation_coinbase.yml
Labels: review-needed

#2915 Update impersonation_chase.yml
  detection-rules/impersonation_chase.yml
Labels: in-test-rules

#2993 Update cc_infra_abuse.yml
  detection-rules/cc_infra_abuse.yml
Labels: in-test-rules, review-needed

#2992 Update link_gammaapp_present.yml
  detection-rules/link_gammaapp_present.yml
Labels: in-test-rules, review-needed

#2888 Create callback_phishing_generic_esignature.yml
  detection-rules/callback_phishing_generic_esignature.yml
Labels: in-test-rules, review-needed

#2895 Excluding disclaimers from thread length and adding doc/docx clause
  detection-rules/attachment_fake_scan_to_email.yml
Labels: in-test-rules, review-needed

#2887 Create callback_phishing_signfree.yml
  detection-rules/callback_phishing_signfree.yml
Labels: in-test-rules, review-needed

#3000 Update impersonation_microsoft.yml
  detection-rules/impersonation_microsoft.yml
Labels: in-test-rules, review-needed

#2997 Updating negation to fall outside of an "or" statement
  detection-rules/brand_impersonation_zoom.yml
Labels: review-needed, hunting-required

#3006 Update brand_impersonation_irs.yml
  detection-rules/brand_impersonation_irs.yml
Labels: in-test-rules, review-needed

#3005 Update attachment_sus_employee_doc.yml
  detection-rules/attachment_sus_employee_doc.yml
Labels: in-test-rules, review-needed

#2918 Create link_onion.yml
  detection-rules/link_onion.yml
Labels: in-test-rules, review-needed

#2886 Create callback_phishing_signable.yml
  detection-rules/callback_phishing_signable.yml
Labels: in-test-rules, review-needed

#3026 Update comp_review_qr_attached_eml.yml
  detection-rules/comp_review_qr_attached_eml.yml
Labels: in-test-rules, review-needed

#3015 Update brand_impersonation_booking_com.yml
  detection-rules/brand_impersonation_booking_com.yml
Labels: in-test-rules, review-needed

#3031 Adding additional keywords to cred theft e-sign rule
  detection-rules/credential_phishing_esign_document_notification.yml
Labels: in-test-rules, review-needed
