Repository sublime-security/sublime-rules, pull requests merged in 2025-01, with the labels that each got.

#2244 create insights - Org Domains Inbound Pass Auth
  insights/authentication/org_inbound_auth_pass.yml
Labels: review-needed

#2095 Create spam_item_giveaway.yml
  detection-rules/spam_item_giveaway.yml
Labels: in-test-rules, review-needed

#2256 Update abuse_google_drive_unsolicited_reply-to.yml
  detection-rules/abuse_google_drive_unsolicited_reply-to.yml
Labels: review-needed

#2092 Update impersonation_dhl.yml
  detection-rules/impersonation_dhl.yml
Labels: in-test-rules, review-needed

#2248 Update open_redirect_emp-eduyield.yml
  detection-rules/open_redirect_emp-eduyield.yml
Labels: review-needed

#2090 standardize docusign auth check
  detection-rules/callback_phishing_docusign_comment.yml
  detection-rules/docusign_new_sender_domain.yml
  detection-rules/link_multistage_docusign.yml
Labels: review-needed

#2254 Create open_redirect_xfinity.yml
  detection-rules/open_redirect_xfinity.yml
Labels: in-test-rules, review-needed

#2253 Create open_redirect_nowlifestyle.yml
  detection-rules/open_redirect_nowlifestyle.yml
Labels: in-test-rules, review-needed

#2260 Update link_multistage_docusign.yml
  detection-rules/link_multistage_docusign.yml
Labels: review-needed

#2259 Update impersonation_ledger.yml
  detection-rules/impersonation_ledger.yml
Labels: review-needed

#2249 Create open_redirect_xfinity_cmp.yml
  detection-rules/open_redirect_xfinity_cmp.yml
Labels: in-test-rules, review-needed

#2264 Update impersonation_sharefile.yml
  detection-rules/impersonation_sharefile.yml
Labels: review-needed

#2267 Update impersonation_docusign.yml
  detection-rules/impersonation_docusign.yml
Labels: review-needed

#2266 Update impersonation_amazon.yml
  detection-rules/impersonation_amazon.yml
Labels: review-needed

#2269 Update ms_infrastructure_abuse.yml
  detection-rules/ms_infrastructure_abuse.yml
Labels: review-needed

#2271 Update callback_phishing_intuit.yml
  detection-rules/callback_phishing_intuit.yml
Labels: review-needed

#2270 Update link_sharepoint_sus_name.yml
  detection-rules/link_sharepoint_sus_name.yml
Labels: review-needed

#2275 Update impersonation_sharepoint_fake_file_share.yml
  detection-rules/impersonation_sharepoint_fake_file_share.yml
Labels: review-needed

#2276 Update spam_item_giveaway.yml
  detection-rules/spam_item_giveaway.yml
Labels: review-needed

#2277 Update spam_attendee_list_solicitation.yml
  detection-rules/spam_attendee_list_solicitation.yml
Labels: review-needed

#2279 Update impersonation_stripe.yml
  detection-rules/impersonation_stripe.yml
Labels: review-needed

#2278 Update impersonation_human_resources.yml
  detection-rules/impersonation_human_resources.yml
Labels: review-needed

#2284 Update brand_impersonation_siriusxm.yml
  detection-rules/brand_impersonation_siriusxm.yml
Labels: review-needed

#2186 Create abuse_google_drive_new_sender_domain.yml
  detection-rules/abuse_google_drive_new_sender_domain.yml
Labels: in-test-rules, review-needed

#2159 Create spam_google_group_invite.yml
  detection-rules/spam_google_group_explict_invite.yml
Labels: in-test-rules, review-needed

#2288 Update spam_attendee_list_solicitation.yml
  detection-rules/spam_attendee_list_solicitation.yml
Labels: review-needed

#2179 Update link_google_open_redirect_with_suspicious_indicators.yml
  detection-rules/link_google_open_redirect_with_suspicious_indicators.yml
Labels: in-test-rules, review-needed

#2195 Update link_credential_phishing_voicemail_language.yml
  detection-rules/link_credential_phishing_voicemail_language.yml
Labels: in-test-rules, review-needed

#2287 Update link_google_notification_untrusted_sender.yml
  detection-rules/link_google_notification_untrusted_sender.yml
Labels: review-needed

#2281 Create callback_phishing_zoho.yml
  detection-rules/callback_phishing_zoho.yml
Labels: review-needed

#2296 Update credential_phishing_fake_email_quarantine_notification.yml
  detection-rules/credential_phishing_fake_email_quarantine_notification.yml
Labels: review-needed

#2285 Update impersonation_docusign.yml
  detection-rules/impersonation_docusign.yml
Labels: review-needed

#2300 Update spam_onmicrosoft.yml
  detection-rules/spam_onmicrosoft.yml
Labels: review-needed

#2301 Update impersonation_microsoft_credential_theft.yml
  detection-rules/impersonation_microsoft_credential_theft.yml
Labels: review-needed

#2298 Create mass_outbound_free_file_host.yml
  discovery-rules/mass_outbound_free_file_host.yml
Labels: review-needed, discovery-rule

#2290 Update impersonation_microsoft.yml
  detection-rules/impersonation_microsoft.yml
Labels: review-needed

#2294 Update brand_impersonation_hulu.yml
  detection-rules/brand_impersonation_hulu.yml
Labels: review-needed

#2295 Update link_credential_phishing_voicemail_language.yml
  detection-rules/link_credential_phishing_voicemail_language.yml
Labels: review-needed

#2289 Update cc_infra_abuse.yml
  detection-rules/cc_infra_abuse.yml
Labels: review-needed

#2293 Create sender_name_confusables.yml
  insights/sender/sender_name_confusables.yml
Labels: review-needed

#2302 Create reply_to_invalid.yml
  insights/headers/reply_to_invalid.yml
Labels: review-needed

#2303 Update spam_image_hidden_element.yml
  detection-rules/spam_image_hidden_element.yml
Labels: in-test-rules, review-needed

#2304 Update spam_google_group_explict_invite.yml
  detection-rules/spam_google_group_explict_invite.yml
Labels: review-needed

#2306 Update file_sharing_link_from_suspicious_sender_domain.yml
  detection-rules/file_sharing_link_from_suspicious_sender_domain.yml
Labels: review-needed

#2308 Update impersonation_paypal.yml
  detection-rules/impersonation_paypal.yml
Labels: review-needed

#2309 Update spam_image_hidden_element.yml
  detection-rules/spam_image_hidden_element.yml
Labels: in-test-rules, review-needed

#2312 Update impersonation_wells_fargo.yml
  detection-rules/impersonation_wells_fargo.yml
Labels: review-needed

#2314 Update link_credential_phishing_voicemail_language.yml
  detection-rules/link_credential_phishing_voicemail_language.yml
Labels: review-needed

#2255 Create impersonation_chrome_web_store_policy.yml
  detection-rules/impersonation_chrome_web_store_policy.yml
Labels: in-test-rules, review-needed

#2272 Create open_redirect_meta_youtube.yml
  detection-rules/open_redirect_meta_youtube.yml
Labels: in-test-rules, review-needed

#2291 Create open_redirect_youtube_google.yml
  detection-rules/open_redirect_youtube_google.yml
Labels: in-test-rules, review-needed

#2250 Create link_hidden_dir.yml
  detection-rules/link_hidden_dir.yml
Labels: in-test-rules, review-needed

#2299 Create link_userinfo_excessive_padding.yml
  detection-rules/link_userinfo_excessive_padding.yml
Labels: in-test-rules, review-needed

#2274 Update link_fake_storage_alert.yml
  detection-rules/link_fake_storage_alert.yml
Labels: review-needed

#2283 Update link_credential_phishing_voicemail_language.yml
  detection-rules/link_credential_phishing_voicemail_language.yml
Labels: in-test-rules

#2315 Update spam_google_looker_studio_report.yml
  detection-rules/spam_google_looker_studio_report.yml
Labels: review-needed

#2316 Update spam_google_group_explict_invite.yml
  detection-rules/spam_google_group_explict_invite.yml
Labels: review-needed

#2225 Create bec_urgent_suspicious_patterns.yml
  detection-rules/bec_urgent_suspicious_patterns.yml
Labels: in-test-rules, review-needed

#2323 Update body_extortion.yml
  detection-rules/body_extortion.yml
Labels: review-needed

#2324 Update link_userinfo_excessive_padding.yml
  detection-rules/link_userinfo_excessive_padding.yml
Labels: in-test-rules, review-needed

#2321 Update link_sharepoint_sus_name.yml
  detection-rules/link_sharepoint_sus_name.yml
Labels: in-test-rules, review-needed

#2322 Update abuse_dropbox_sus_names.yml
  detection-rules/abuse_dropbox_sus_names.yml
Labels: in-test-rules, review-needed

#2331 Update brand_impersonation_enbridge.yml
  detection-rules/brand_impersonation_enbridge.yml
Labels: review-needed

#2337 Update impersonation_chrome_web_store_policy.yml
  detection-rules/impersonation_chrome_web_store_policy.yml
Labels: review-needed

#2332 Update impersonation_quickbooks.yml
  detection-rules/impersonation_quickbooks.yml
Labels: help wanted, review-needed

#2340 Update open_redirect_emp-eduyield.yml
  detection-rules/open_redirect_emp-eduyield.yml
Labels: review-needed

#2319 Update spam_image_hidden_element.yml
  detection-rules/spam_image_hidden_element.yml
Labels: in-test-rules, review-needed

#2350 Update spam_image_hidden_element.yml
  detection-rules/spam_image_hidden_element.yml
Labels: review-needed

#2328 Create open_redirect_qrxtech.yml
  detection-rules/open_redirect_qrxtech.yml
Labels: in-test-rules, review-needed

#2329 Create open_redirect_magic4media.yml
  detection-rules/open_redirect_magic4media.yml
Labels: in-test-rules, review-needed

#2330 Create open_redirect_designsori.yml
  detection-rules/open_redirect_designsori.yml
Labels: in-test-rules, review-needed

#2351 Update impersonation_netflix.yml
  detection-rules/impersonation_netflix.yml
Labels: review-needed

#2352 Update spam_attendee_list_solicitation.yml
  detection-rules/spam_attendee_list_solicitation.yml
Labels: review-needed

#2354 Update link_credential_phishing_voicemail_language.yml
  detection-rules/link_credential_phishing_voicemail_language.yml
Labels: review-needed

#2341 Create open_redirect_predictiveresponse.yml
  detection-rules/open_redirect_predictiveresponse.yml
Labels: in-test-rules, review-needed

#2325 Create open_redirect_bubblelife.yml
  detection-rules/open_redirect_bubblelife.yml
Labels: in-test-rules, review-needed

#2347 Create open_redirect_k-mil.yml
  detection-rules/open_redirect_k-mil.yml
Labels: in-test-rules, review-needed

#2343 Create open_redirect_plasticsurgery.yml
  detection-rules/open_redirect_plasticsurgery.yml
Labels: in-test-rules, review-needed

#2130 Create impersonation_benefits_enrollment.yml
  detection-rules/impersonation_benefits_enrollment.yml
Labels: in-test-rules, review-needed
